### ISSUE TITLE
How can I debug a bat file

### ISSUE THREAD

**Issue by mt406** [clausb/nclauncher#1]
I was trying to use your bat file but its not working . How can I debug it so that I can fix issues at my end ?

**Comment by clausb** [comment]
Change the first line in the script from "@echo off" to "echo on" (without the quotes, of course), then run the batch file from a command shell window. This will give you a reasonable amount of tracing output which hopefully helps to pin down the issue.

Are you seeing any error messages while executing the script?

**Comment by mt406** [comment]
Thanks for quick reply... 

When I run your .bat its running and suddenly going away.. without any response. (I was unable to debug it , will do it now and check what is correct error ).

I tried this also from cmd ,when I run below code : 

"nclauncher.exe -url https://sa.testing.com -u giantsUser -p password123 -r Users" (with my url,user,password)

I am getting an error "User do not authenticate "

1) We are using "network connect" with "Symentc VIP access" so what may be the correct replacement for string "set realm="SecurID(Network Connect)"  ?

2) What else I need to change in your bat file as per above statement #1

Regards
Manish

**Comment by clausb** [comment]
Manish,

is https://www.symantec.com/vip-authentication-service/ the access solution you mentioned? I am not familiar with the product, but it looks like this is a solution meant to replace the RSA hardware token in a two-factor authentication scheme, is that correct?

I assume that for the actual VPN connection, you are using Juniper's components?

The way I found the right realm string was to glean it from the web UI which my company provided officially. It had a dropdown list of connection options/realms as configured by our IT folks, and one of them was labeled "SecurID(Network Connect". Unfortunately, I cannot look up the details anymore, as I do not work for that company anymore, and my new company has a different VPN solution.

**Comment by mt406** [comment]
Yes , you are correct for VIP access of Symentec.

Yes we are using Juniper connect .

Ok , Fine . That was a useful information . I will work more with info and try to get it done .

Thanks a lot :+1: 

Regards
Manish
